import { JobBooking, SmsThread, MissedCall, TradeService, AssistantSettings, Organization, Customer } from './types';

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    organizationId: 'org-apex',
    name: 'Elena Rostova',
    phone: '+1 (555) 234-8901',
    email: 'elena.r@example.com',
    address: '742 Evergreen Terrace, Springfield',
    notes: 'Gate code 1234. Dog is friendly but loud.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-2',
    organizationId: 'org-apex',
    name: 'Marcus Vance',
    phone: '+1 (555) 349-1122',
    email: 'marcus@vance-elec.com',
    address: '1840 Highland Ridge Dr, Westview',
    notes: 'Main water shutoff is in the utility closet behind the dryer.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 60).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-3',
    organizationId: 'org-apex',
    name: 'Sarah Jenkins',
    phone: '+1 (555) 872-9014',
    email: 'sjenkins@gmail.com',
    address: '429 Birchwood Ln, Oakridge',
    notes: 'Prefer afternoon appointments. Text only.',
    createdAt: new Date(Date.now() - 3600000 * 24 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const initialSettings: AssistantSettings = {
  tradespersonName: 'Mark Kowalski',
  businessName: 'Apex Plumbing & Mechanical',
  tradeType: 'plumbing',
  twilioPhoneNumber: '+1 (555) 782-4309',
  forwardCallsTo: '+1 (555) 438-9210',
  aiTone: 'friendly_direct',
  autoConfirmRoutine: true,
  bufferMinutesBetweenJobs: 45,
  workingHours: {
    start: '07:30',
    end: '17:30',
    workWeekends: false,
  },
  emergencyKeywords: ['flood', 'burst pipe', 'sewage', 'sparking', 'no heat', 'carbon monoxide', 'water main'],
  llmProvider: 'openai_compatible',
  openaiBaseUrl: 'https://9router-production-a99a.up.railway.app/v1',
  openaiApiKey: 'sk-0d71fb7c21ea2f91-mv2hhc-443a0a26',
  openaiModel: 'gemini/gemini-3.8-flash',
};

export const initialServices: TradeService[] = [
  {
    id: 'srv-1',
    title: 'Water Heater Replacement / Diagnostic',
    trade: 'plumbing',
    durationHours: 2.5,
    basePrice: 420,
    description: 'Diagnose pilot assembly, heating elements, or full 50-gal tank replacement installation.',
    isPopular: true,
  },
  {
    id: 'srv-2',
    title: 'Main Line Drain Snaking / Hydrojet',
    trade: 'plumbing',
    durationHours: 1.5,
    basePrice: 285,
    description: 'Camera inspection + heavy duty 100ft snake rooter for slow or backed-up main sewer cleanout.',
    isPopular: true,
  },
  {
    id: 'srv-3',
    title: 'Emergency Burst Pipe & Valve Shutoff',
    trade: 'plumbing',
    durationHours: 2.0,
    basePrice: 380,
    description: 'Immediate dispatch for active interior leaks, broken copper/PEX fittings, and pressure relief failures.',
    isPopular: true,
  },
  {
    id: 'srv-4',
    title: 'Garbage Disposal & Kitchen Faucet Swap',
    trade: 'plumbing',
    durationHours: 1.0,
    basePrice: 195,
    description: 'Replacement of jammed 1/2 HP Badger or leaky pull-down kitchen faucet assembly.',
  },
  {
    id: 'srv-5',
    title: 'Whole-Home Pressure Regulator (PRV) Replacement',
    trade: 'plumbing',
    durationHours: 1.5,
    basePrice: 340,
    description: 'Replace failed Wilkins/Watts PRV causing high municipal pressure spike & banging pipes.',
  },
  {
    id: 'srv-6',
    title: 'Electrical Panel Inspection & Breaker Replacement',
    trade: 'electrical',
    durationHours: 2.0,
    basePrice: 320,
    description: '200A panel audit, tandem breaker addition, thermal imaging for hot busbars.',
  },
  {
    id: 'srv-7',
    title: 'HVAC Seasonal Tune-up & Capacitor Test',
    trade: 'hvac',
    durationHours: 1.5,
    basePrice: 210,
    description: 'Clean condenser coils, test dual run capacitor microfarads, delta T airflow audit.',
  }
];

export const initialBookings: JobBooking[] = [
  {
    id: 'bk-101',
    customerName: 'Elena Rostova',
    customerPhone: '+1 (555) 234-8901',
    address: '742 Evergreen Terrace, Springfield',
    tradeType: 'plumbing',
    serviceTitle: 'Main Line Drain Snaking / Hydrojet',
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: '08:30 AM - 10:30 AM',
    status: 'completed',
    estimateAmount: 285,
    notes: 'Downstairs bathroom shower backing up with gray water. Cleanout located next to water meter.',
    urgency: 'urgent',
    createdFrom: 'sms',
    smsThreadId: 'th-1',
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'bk-102',
    customerName: 'Marcus Vance',
    customerPhone: '+1 (555) 349-1122',
    address: '1840 Highland Ridge Dr, Westview',
    tradeType: 'plumbing',
    serviceTitle: 'Water Heater Replacement / Diagnostic',
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: '11:15 AM - 01:45 PM',
    status: 'in_progress',
    estimateAmount: 650,
    notes: 'Rheem 50-gal electric water heater throwing fault code 3. Mark is on-site draining unit.',
    urgency: 'routine',
    createdFrom: 'missed_call',
    smsThreadId: 'th-2',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'bk-103',
    customerName: 'Sarah Jenkins',
    customerPhone: '+1 (555) 872-9014',
    address: '429 Birchwood Ln, Oakridge',
    tradeType: 'plumbing',
    serviceTitle: 'Garbage Disposal & Kitchen Faucet Swap',
    date: new Date().toISOString().split('T')[0], // Today
    timeSlot: '02:30 PM - 03:45 PM',
    status: 'scheduled',
    estimateAmount: 195,
    notes: 'Customer bought Moen Adler faucet and InSinkErator Badger 500, needs professional install.',
    urgency: 'routine',
    createdFrom: 'sms',
    smsThreadId: 'th-3',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  // Day -1 (Yesterday)
  {
    id: 'bk-091',
    customerName: 'Gregory House',
    customerPhone: '+1 (555) 312-9844',
    address: '102 Princeton Ave, Mercer',
    tradeType: 'plumbing',
    serviceTitle: 'Emergency Burst Pipe & Valve Shutoff',
    date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0],
    timeSlot: '09:00 AM - 11:00 AM',
    status: 'completed',
    estimateAmount: 380,
    notes: 'Freezer line split behind drywall. Replaced with braided stainless steel line.',
    urgency: 'emergency',
    createdFrom: 'missed_call',
    createdAt: new Date(Date.now() - 86400000 * 1 - 3600000 * 6).toISOString(),
  },
  {
    id: 'bk-092',
    customerName: 'Maya Lin',
    customerPhone: '+1 (555) 472-1190',
    address: '55 Stonebridge Way, Lakeview',
    tradeType: 'plumbing',
    serviceTitle: 'Garbage Disposal & Kitchen Faucet Swap',
    date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0],
    timeSlot: '01:30 PM - 02:45 PM',
    status: 'completed',
    estimateAmount: 240,
    notes: 'Kitchen sink basket strainer leak and Badger 5 installation.',
    urgency: 'routine',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 1 - 3600000 * 4).toISOString(),
  },
  // Day -2
  {
    id: 'bk-081',
    customerName: 'Arthur Dent',
    customerPhone: '+1 (555) 831-4455',
    address: '42 Meadow Ln, Cottington',
    tradeType: 'plumbing',
    serviceTitle: 'Main Line Drain Snaking / Hydrojet',
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    timeSlot: '08:00 AM - 10:00 AM',
    status: 'completed',
    estimateAmount: 450,
    notes: 'Tree root intrusion cleared with hydro-jetter 80 feet out.',
    urgency: 'urgent',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 2 - 3600000 * 8).toISOString(),
  },
  {
    id: 'bk-082',
    customerName: 'Claire Redfield',
    customerPhone: '+1 (555) 902-6712',
    address: '304 Raccoon St, Arklay',
    tradeType: 'plumbing',
    serviceTitle: 'Whole-Home Pressure Regulator (PRV) Replacement',
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    timeSlot: '11:00 AM - 12:30 PM',
    status: 'completed',
    estimateAmount: 290,
    notes: 'Replaced failed Wilkins 1-inch regulator. Pressure adjusted to 60 PSI.',
    urgency: 'routine',
    createdFrom: 'missed_call',
    createdAt: new Date(Date.now() - 86400000 * 2 - 3600000 * 5).toISOString(),
  },
  {
    id: 'bk-083',
    customerName: 'Samwise Gamgee',
    customerPhone: '+1 (555) 771-3329',
    address: '1 Shire Way, Bywater',
    tradeType: 'plumbing',
    serviceTitle: 'Garbage Disposal & Kitchen Faucet Swap',
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    timeSlot: '02:00 PM - 03:00 PM',
    status: 'completed',
    estimateAmount: 195,
    notes: 'P-trap realignment and pull-down faucet swap.',
    urgency: 'routine',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 2 - 3600000 * 2).toISOString(),
  },
  // Day -3
  {
    id: 'bk-071',
    customerName: 'Bruce Wayne',
    customerPhone: '+1 (555) 998-1007',
    address: '1007 Mountain Dr, Gotham',
    tradeType: 'plumbing',
    serviceTitle: 'Water Heater Replacement / Diagnostic',
    date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0],
    timeSlot: '09:00 AM - 11:30 AM',
    status: 'completed',
    estimateAmount: 520,
    notes: 'Replaced upper and lower heating elements + thermostat.',
    urgency: 'urgent',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 3 - 3600000 * 7).toISOString(),
  },
  {
    id: 'bk-072',
    customerName: 'Diana Prince',
    customerPhone: '+1 (555) 623-8841',
    address: '77 Gateway Blvd, Gateway City',
    tradeType: 'plumbing',
    serviceTitle: 'Whole-Home Pressure Regulator (PRV) Replacement',
    date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0],
    timeSlot: '01:00 PM - 02:30 PM',
    status: 'completed',
    estimateAmount: 340,
    notes: 'High pressure spike 105 PSI causing thermal expansion tank failure.',
    urgency: 'routine',
    createdFrom: 'missed_call',
    createdAt: new Date(Date.now() - 86400000 * 3 - 3600000 * 3).toISOString(),
  },
  // Day -4
  {
    id: 'bk-061',
    customerName: 'Tony Stark',
    customerPhone: '+1 (555) 431-7788',
    address: '10880 Malibu Point, Malibu',
    tradeType: 'plumbing',
    serviceTitle: 'Main Line Drain Snaking / Hydrojet',
    date: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0],
    timeSlot: '10:00 AM - 12:00 PM',
    status: 'completed',
    estimateAmount: 285,
    notes: 'Garage workshop cleanout cleared of sediment build-up.',
    urgency: 'urgent',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 4 - 3600000 * 6).toISOString(),
  },
  {
    id: 'bk-062',
    customerName: 'Peter Parker',
    customerPhone: '+1 (555) 209-1962',
    address: '20 Ingram St, Forest Hills',
    tradeType: 'plumbing',
    serviceTitle: 'Garbage Disposal & Kitchen Faucet Swap',
    date: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0],
    timeSlot: '02:00 PM - 03:00 PM',
    status: 'completed',
    estimateAmount: 210,
    notes: 'Jammed disposal cleared and unjam wrench provided to tenant.',
    urgency: 'routine',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 4 - 3600000 * 2).toISOString(),
  },
  // Day -5
  {
    id: 'bk-051',
    customerName: 'Clark Kent',
    customerPhone: '+1 (555) 789-0012',
    address: '344 Clinton St, Metropolis',
    tradeType: 'plumbing',
    serviceTitle: 'Water Heater Replacement / Diagnostic',
    date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    timeSlot: '08:30 AM - 11:00 AM',
    status: 'completed',
    estimateAmount: 620,
    notes: 'New Bradford White 50-gallon gas tank installed with earthquake straps.',
    urgency: 'urgent',
    createdFrom: 'missed_call',
    createdAt: new Date(Date.now() - 86400000 * 5 - 3600000 * 8).toISOString(),
  },
  {
    id: 'bk-052',
    customerName: 'Lois Lane',
    customerPhone: '+1 (555) 789-0013',
    address: '344 Clinton St, Metropolis',
    tradeType: 'plumbing',
    serviceTitle: 'Emergency Burst Pipe & Valve Shutoff',
    date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    timeSlot: '11:30 AM - 01:00 PM',
    status: 'completed',
    estimateAmount: 310,
    notes: 'Laundry box quarter-turn valve repacked and tested.',
    urgency: 'emergency',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 5 - 3600000 * 5).toISOString(),
  },
  {
    id: 'bk-053',
    customerName: 'Barry Allen',
    customerPhone: '+1 (555) 321-4321',
    address: '500 Central Ave, Central City',
    tradeType: 'plumbing',
    serviceTitle: 'Whole-Home Pressure Regulator (PRV) Replacement',
    date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    timeSlot: '02:00 PM - 03:30 PM',
    status: 'completed',
    estimateAmount: 220,
    notes: 'Installed inline pressure gauge and tested static flow rate.',
    urgency: 'routine',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 5 - 3600000 * 2).toISOString(),
  },
  // Day -6
  {
    id: 'bk-041',
    customerName: 'Natasha Romanoff',
    customerPhone: '+1 (555) 890-5544',
    address: '124 Hudson St, Manhattan',
    tradeType: 'plumbing',
    serviceTitle: 'Emergency Burst Pipe & Valve Shutoff',
    date: new Date(Date.now() - 86400000 * 6).toISOString().split('T')[0],
    timeSlot: '09:00 AM - 11:00 AM',
    status: 'completed',
    estimateAmount: 410,
    notes: 'Basement ceiling copper fitting soldered and insulated.',
    urgency: 'emergency',
    createdFrom: 'missed_call',
    createdAt: new Date(Date.now() - 86400000 * 6 - 3600000 * 7).toISOString(),
  },
  {
    id: 'bk-042',
    customerName: 'Steve Rogers',
    customerPhone: '+1 (555) 194-1776',
    address: '569 Fulton St, Brooklyn',
    tradeType: 'plumbing',
    serviceTitle: 'Main Line Drain Snaking / Hydrojet',
    date: new Date(Date.now() - 86400000 * 6).toISOString().split('T')[0],
    timeSlot: '01:00 PM - 03:00 PM',
    status: 'completed',
    estimateAmount: 350,
    notes: 'Cast iron sewer main camera inspected and cleared of scale.',
    urgency: 'urgent',
    createdFrom: 'sms',
    createdAt: new Date(Date.now() - 86400000 * 6 - 3600000 * 3).toISOString(),
  },
  // Upcoming Tomorrow
  {
    id: 'bk-104',
    customerName: 'David Thorne',
    customerPhone: '+1 (555) 912-3344',
    address: '88 Meadowbrook Way, Fairview',
    tradeType: 'plumbing',
    serviceTitle: 'Emergency Burst Pipe & Valve Shutoff',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    timeSlot: '09:00 AM - 11:00 AM',
    status: 'scheduled',
    estimateAmount: 420,
    notes: 'Rescheduled from today via SMS! Copper pinhole leak under crawlspace; main shutoff secured.',
    urgency: 'urgent',
    createdFrom: 'sms',
    smsThreadId: 'th-4',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'bk-105',
    customerName: 'Linda Chen',
    customerPhone: '+1 (555) 441-2098',
    address: '1104 Sycamore Creek Ct, Springfield',
    tradeType: 'plumbing',
    serviceTitle: 'Whole-Home Pressure Regulator (PRV) Replacement',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    timeSlot: '01:00 PM - 02:30 PM',
    status: 'scheduled',
    estimateAmount: 340,
    notes: 'Municipal water pressure gauge reading 98 PSI. Toilet fill valves squealing under pressure.',
    urgency: 'routine',
    createdFrom: 'missed_call',
    smsThreadId: 'th-5',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  }
];

export const initialThreads: SmsThread[] = [
  {
    id: 'th-1',
    customerName: 'Elena Rostova',
    customerPhone: '+1 (555) 234-8901',
    address: '742 Evergreen Terrace, Springfield',
    tradeType: 'plumbing',
    unreadCount: 0,
    lastActivity: '10:45 AM',
    status: 'booked',
    bookingId: 'bk-101',
    messages: [
      {
        id: 'm1-1',
        threadId: 'th-1',
        sender: 'customer',
        text: 'Hi Mark, our downstairs shower is backing up whenever someone runs the laundry. Can someone look at this today?',
        timestamp: '07:15 AM',
        status: 'read',
        parsedIntent: { intent: 'book', urgency: 'urgent', serviceType: 'Main line drain rooter' }
      },
      {
        id: 'm1-2',
        threadId: 'th-1',
        sender: 'assistant',
        text: 'Good morning Elena! This is Mark\'s automated scheduling assistant with Apex Plumbing. That sounds like a main sewer line backup. I have an opening this morning at 8:30 AM or afternoon at 2:30 PM. Would 8:30 AM work to get a technician out?',
        timestamp: '07:16 AM',
        status: 'delivered',
        actionTag: 'slot_offered'
      },
      {
        id: 'm1-3',
        threadId: 'th-1',
        sender: 'customer',
        text: '8:30 AM is perfect please! We are at 742 Evergreen Terrace.',
        timestamp: '07:18 AM',
        status: 'read',
        parsedIntent: { intent: 'confirm', requestedTime: '08:30 AM' }
      },
      {
        id: 'm1-4',
        threadId: 'th-1',
        sender: 'assistant',
        text: 'You\'re booked for today, 8:30 AM - 10:30 AM at 742 Evergreen Terrace. Mark will text you when he\'s 15 mins out with the service truck. Estimated inspection & snaking is $285.',
        timestamp: '07:18 AM',
        status: 'delivered',
        actionTag: 'auto_booked'
      }
    ]
  },
  {
    id: 'th-4',
    customerName: 'David Thorne',
    customerPhone: '+1 (555) 912-3344',
    address: '88 Meadowbrook Way, Fairview',
    tradeType: 'plumbing',
    unreadCount: 0,
    lastActivity: '11:20 AM',
    status: 'rescheduled',
    bookingId: 'bk-104',
    messages: [
      {
        id: 'm4-1',
        threadId: 'th-4',
        sender: 'customer',
        text: 'Hey Mark, something urgent came up at work. Can we reschedule today\'s crawlspace pipe repair to tomorrow morning around 9 or 10am instead?',
        timestamp: '11:18 AM',
        status: 'read',
        parsedIntent: {
          intent: 'reschedule',
          urgency: 'urgent',
          requestedTime: 'Tomorrow morning 9-10 AM'
        }
      },
      {
        id: 'm4-2',
        threadId: 'th-4',
        sender: 'assistant',
        text: 'No problem David! I checked Mark\'s route for tomorrow and moved your crawlspace pipe repair to tomorrow morning from 9:00 AM - 11:00 AM at 88 Meadowbrook Way. Did you shut off the gate valve in the meantime?',
        timestamp: '11:19 AM',
        status: 'delivered',
        actionTag: 'rescheduled'
      },
      {
        id: 'm4-3',
        threadId: 'th-4',
        sender: 'customer',
        text: 'Yes, main valve is turned 90 degrees and bucket is underneath. See you tomorrow at 9, thanks for the quick reply!',
        timestamp: '11:20 AM',
        status: 'read'
      }
    ]
  },
  {
    id: 'th-2',
    customerName: 'Marcus Vance',
    customerPhone: '+1 (555) 349-1122',
    address: '1840 Highland Ridge Dr, Westview',
    tradeType: 'plumbing',
    unreadCount: 0,
    lastActivity: '09:40 AM',
    status: 'booked',
    bookingId: 'bk-102',
    messages: [
      {
        id: 'm2-1',
        threadId: 'th-2',
        sender: 'assistant',
        text: 'Hey Marcus, sorry Mark missed your call! He is currently under a house on an emergency call. What can we help you with today? Reply here to schedule directly.',
        timestamp: '09:22 AM',
        status: 'delivered',
        actionTag: 'info_requested'
      },
      {
        id: 'm2-2',
        threadId: 'th-2',
        sender: 'customer',
        text: 'Water heater in our utility closet is leaking from the bottom base. Floor is soaking. Need someone ASAP.',
        timestamp: '09:24 AM',
        status: 'read',
        parsedIntent: { intent: 'emergency', urgency: 'emergency', serviceType: 'Leaking water heater' }
      },
      {
        id: 'm2-3',
        threadId: 'th-2',
        sender: 'assistant',
        text: 'Got it Marcus. First, please turn off the cold water shutoff valve at the top of the heater. Mark can arrive today at 11:15 AM - 1:45 PM. What is your street address?',
        timestamp: '09:25 AM',
        status: 'delivered',
        actionTag: 'emergency_escalated'
      },
      {
        id: 'm2-4',
        threadId: 'th-2',
        sender: 'customer',
        text: '1840 Highland Ridge Dr in Westview. Cold valve is turned off now.',
        timestamp: '09:26 AM',
        status: 'read'
      },
      {
        id: 'm2-5',
        threadId: 'th-2',
        sender: 'assistant',
        text: 'All set! You\'re locked in for 11:15 AM today at 1840 Highland Ridge Dr. Mark has your details and parts on the truck.',
        timestamp: '09:27 AM',
        status: 'delivered',
        actionTag: 'auto_booked'
      }
    ]
  },
  {
    id: 'th-3',
    customerName: 'Sarah Jenkins',
    customerPhone: '+1 (555) 872-9014',
    address: '429 Birchwood Ln, Oakridge',
    tradeType: 'plumbing',
    unreadCount: 1,
    lastActivity: '11:45 AM',
    status: 'booked',
    bookingId: 'bk-103',
    messages: [
      {
        id: 'm3-1',
        threadId: 'th-3',
        sender: 'customer',
        text: 'Hi! How much do you charge to install a customer-supplied kitchen faucet and Badger garbage disposal?',
        timestamp: '11:40 AM',
        status: 'read',
        parsedIntent: { intent: 'inquiry', serviceType: 'Faucet & disposal installation' }
      },
      {
        id: 'm3-2',
        threadId: 'th-3',
        sender: 'assistant',
        text: 'Hi Sarah! For customer-supplied faucet & garbage disposal install, our flat rate is $195 which includes testing, new plumber\'s putty, and disposal gasket. Mark has a slot this afternoon at 2:30 PM. Would you like that spot?',
        timestamp: '11:41 AM',
        status: 'delivered',
        actionTag: 'quote_given'
      },
      {
        id: 'm3-3',
        threadId: 'th-3',
        sender: 'customer',
        text: 'Yes please! 2:30 PM works. Address is 429 Birchwood Ln.',
        timestamp: '11:45 AM',
        status: 'sent'
      }
    ]
  }
];

export const initialMissedCalls: MissedCall[] = [
  {
    id: 'mc-1',
    callerName: 'Marcus Vance',
    callerPhone: '+1 (555) 349-1122',
    timestamp: '09:21 AM',
    durationSeconds: 18,
    voicemailTranscript: 'Hey Mark, Marcus Vance here. My water heater in the utility closet is pooling water all over the floor. Give me a call back or let me know if you can come today.',
    autoSmsSent: true,
    autoSmsTimestamp: '09:22 AM (11s later)',
    autoSmsReplyReceived: true,
    convertedToBooking: true,
    bookingId: 'bk-102',
    urgency: 'emergency',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mc-2',
    callerName: 'Linda Chen',
    callerPhone: '+1 (555) 441-2098',
    timestamp: '08:04 AM',
    durationSeconds: 24,
    voicemailTranscript: 'Hi, I need someone to look at my pressure reducing valve, the water pressure is rattling the pipes through the whole house. 1104 Sycamore Creek.',
    autoSmsSent: true,
    autoSmsTimestamp: '08:04 AM (9s later)',
    autoSmsReplyReceived: true,
    convertedToBooking: true,
    bookingId: 'bk-105',
    urgency: 'routine',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mc-3',
    callerName: 'Robert Gallagher',
    callerPhone: '+1 (555) 603-7721',
    timestamp: '10:55 AM',
    durationSeconds: 12,
    voicemailTranscript: 'Looking for a rough-in estimate for adding a half bath in the basement.',
    autoSmsSent: true,
    autoSmsTimestamp: '10:55 AM (8s later)',
    autoSmsReplyReceived: false,
    convertedToBooking: false,
    urgency: 'routine',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mc-4',
    callerName: 'Gregory House',
    callerPhone: '+1 (555) 312-9844',
    timestamp: 'Yesterday, 08:45 AM',
    durationSeconds: 15,
    voicemailTranscript: 'Active leak under refrigerator, need someone before noon.',
    autoSmsSent: true,
    autoSmsTimestamp: 'Yesterday, 08:45 AM (9s later)',
    autoSmsReplyReceived: true,
    convertedToBooking: true,
    bookingId: 'bk-091',
    urgency: 'emergency',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'mc-5',
    callerName: 'Claire Redfield',
    callerPhone: '+1 (555) 902-6712',
    timestamp: '2 days ago, 10:30 AM',
    durationSeconds: 20,
    voicemailTranscript: 'Pressure valve is whistling very loudly.',
    autoSmsSent: true,
    autoSmsTimestamp: '2 days ago, 10:30 AM',
    autoSmsReplyReceived: true,
    convertedToBooking: true,
    bookingId: 'bk-082',
    urgency: 'routine',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'mc-6',
    callerName: 'Diana Prince',
    callerPhone: '+1 (555) 623-8841',
    timestamp: '3 days ago, 12:15 PM',
    durationSeconds: 22,
    voicemailTranscript: 'Need high water pressure looked at soon.',
    autoSmsSent: true,
    autoSmsTimestamp: '3 days ago, 12:15 PM',
    autoSmsReplyReceived: true,
    convertedToBooking: true,
    bookingId: 'bk-072',
    urgency: 'routine',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'mc-7',
    callerName: 'Clark Kent',
    callerPhone: '+1 (555) 789-0012',
    timestamp: '5 days ago, 08:00 AM',
    durationSeconds: 30,
    voicemailTranscript: 'Water heater pilot will not stay lit, need replacement.',
    autoSmsSent: true,
    autoSmsTimestamp: '5 days ago, 08:00 AM',
    autoSmsReplyReceived: true,
    convertedToBooking: true,
    bookingId: 'bk-051',
    urgency: 'urgent',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'mc-8',
    callerName: 'Natasha Romanoff',
    callerPhone: '+1 (555) 890-5544',
    timestamp: '6 days ago, 08:30 AM',
    durationSeconds: 16,
    voicemailTranscript: 'Burst pipe dripping into basement.',
    autoSmsSent: true,
    autoSmsTimestamp: '6 days ago, 08:30 AM',
    autoSmsReplyReceived: true,
    convertedToBooking: true,
    bookingId: 'bk-041',
    urgency: 'emergency',
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  }
];

export const initialOrganizations: Organization[] = [
  {
    id: 'org-apex',
    name: 'Apex Plumbing & Mechanical',
    trade: 'plumbing',
    technicianName: 'Mark Kowalski',
    plan: 'Solo Pro',
    twilioPhoneNumber: '+1 (555) 782-4309',
  },
  {
    id: 'org-summit',
    name: 'Summit HVAC & Thermal',
    trade: 'hvac',
    technicianName: 'Mark Kowalski',
    plan: 'Growth',
    twilioPhoneNumber: '+1 (555) 890-2341',
  },
  {
    id: 'org-vance',
    name: 'Vance Electrical & EV Charging',
    trade: 'electrical',
    technicianName: 'Marcus Vance',
    plan: 'Solo Pro',
    twilioPhoneNumber: '+1 (555) 349-1122',
  },
];

